<!DOCTYPE html>
<html>
<head>
	<title>Slim Wiki</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/main.css" />
	<link rel="stylesheet" type="text/css" href="css/simplemde.min.css" />
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
	<body>
		<div class="container-fluid main">
			<div class="row">
				<div class="col-xs-12 col-md-3" id="sidebar2"></div>
				<div class="col-xs-12 col-md-9" id="container"></div>
			</div>
		</div>

		<script type="text/javascript" src="js/app.js"></script>
		<script type="text/javascript" src="js/simplemde.min.js"></script>
	</body>
</html>